version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"  # Group all Actions updates into a single larger pull request
    schedule:
      interval: "weekly"
# ID-1768294488-15b5c6fa
