---
dir: testing
filename: mocks.go
pkgname: testing
template: testify
template-data:
  boilerplate-file: ../../../../hack/boilerplate/boilerplate.generatego.txt
  unroll-variadic: true
packages:
  k8s.io/kubernetes/pkg/kubelet/server/stats:
    interfaces:
      Provider: {}
      SummaryProvider: {}
# ID-1768294461-3d3d7114
