---
dir: testing
filename: mocks.go
pkgname: testing
template: testify
template-data:
  boilerplate-file: ../../../hack/boilerplate/boilerplate.generatego.txt
  unroll-variadic: true
packages:
  k8s.io/kubernetes/pkg/kubelet/status:
    interfaces:
      PodStatusProvider: {}
# ID-1768294481-85653140
